export const GET_BEST_WTITERS = 'GET_BEST_WTITERS';
export const BEST_WTITERS_LOADING_NOW = 'BEST_WTITERS_LOADING_NOW';
export const BEST_WTITERS_LOADING_FINISH = 'BEST_WTITERS_LOADING_FINISH';
export const BEST_WTITERS_ERROR_HAPPEN = 'BEST_WTITERS_ERROR_HAPPEN';
export const BEST_WTITERS_NOT_ERROR = 'BEST_WTITERS_NOT_ERROR';
