

export const USER_EDIT_INFO_SUCCESS = 'USER_EDIT_INFO_SUCCESS';
export const USER_EDIT_INFO_FAILURE = 'USER_EDIT_INFO_FAILURE';
export const CLEAR_USER_EDIT_INFO_ERROR = 'CLEAR_USER_EDIT_INFO_ERROR';