

export const GET_USER_SAVED_ARTICLES_SUCCESS = 'GET_USER_SAVED_ARTICLES_SUCCESS';
export const GET_USER_SAVED_ARTICLES_LOADING_START = 'GET_USER_SAVED_ARTICLES_LOADING_START';
export const GET_USER_SAVED_ARTICLES_FAILURE = 'GET_USER_SAVED_ARTICLES_FAILURE';

