
export const GET_TOP_READING = 'GET_TOP_READING';
export const TOP_READING_LOADING_NOW = 'TOP_READING_LOADING_NOW';
export const TOP_READING_LOADING_FINISH = '  TOP_READING_LOADING_FINISH';
export const TOP_READING_ERROR_HAPPEN = '  TOP_READING_ERROR_HAPPEN';
export const TOP_READING_NOT_ERROR = '  TOP_READING_NOT_ERROR';
