
export const DELETE_ARTICLE_SUCCESS = 'DELETE_ARTICLE_SUCCESS';
export const DELETE_ARTICLE_FAILURE = 'DELETE_ARTICLE_FAILURE';

export const LIKE_ARTICLE_SUCCESS = 'LIKE_ARTICLE_SUCCESS';
export const LIKE_ARTICLE_FAILURE = 'LIKE_ARTICLE_FAILURE';

export const REMOVE_LIKE_ARTICLE_SUCCESS = 'REMOVE_LIKE_ARTICLE_SUCCESS';
export const REMOVE_LIKE_ARTICLE_FAILURE = 'REMOVE_LIKE_ARTICLE_FAILURE';

export const DISLIKE_ARTICLE_SUCCESS = 'DISLIKE_ARTICLE_SUCCESS';
export const DISLIKE_ARTICLE_FAILURE = 'DISLIKE_ARTICLE_FAILURE';

export const REMOVE_DISLIKE_ARTICLE_SUCCESS = 'REMOVE_DISLIKE_ARTICLE_SUCCESS';
export const REMOVE_DISLIKE_ARTICLE_FAILURE = 'REMOVE_DISLIKE_ARTICLE_FAILURE';

export const SAVE_ARTICLE_SUCCESS = 'SAVE_ARTICLE_SUCCESS';
export const SAVE_ARTICLE_FAILURE = 'SAVE_ARTICLE_FAILURE';

export const REMOVE_SAVE_ARTICLE_SUCCESS = 'REMOVE_SAVE_ARTICLE_SUCCESS';
export const REMOVE_SAVE_ARTICLE_FAILURE = 'REMOVE_SAVE_ARTICLE_FAILURE';

export const SHARE_ARTICLE_SUCCESS = 'SHARE_ARTICLE';
export const SHARE_ARTICLE_FAILURE = 'SHARE_ARTICLE_FAILURE';

export const CLEAR_ARTICLE_ACTION_ERROR = 'CLEAR_ARTICLE_ACTION_ERROR';
