
export const GET_TOP_READING_ARTICLES_SUCCESS = 'GET_TOP_READING_ARTICLES_SUCCESS';
export const GET_TOP_READING_ARTICLES_FAILURE = 'GET_TOP_READING_ARTICLES_FAILURE';
export const GET_TOP_READING_ARTICLES_LOADING_START = 'GET_TOP_READING_ARTICLES_LOADING_START';

