

export const AUTHENTICATE_MAIN_USER_SUCCESS = 'AUTHENTICATE_MAIN_USER_SUCCESS';
export const AUTHENTICATE_MAIN_USER_START = 'AUTHENTICATE_MAIN_USER_START';
export const AUTHENTICATE_MAIN_USER_FAILURE = '  MAIN_USER_ERROR_HAPPEN';
export const SIGN_FAILURE = 'SIGN_FAILURE';
export const SIGN_SUCCESS = 'SIGN_SUCCESS';
export const SIGN_OUT = 'SIGN_OUT';
export const CLEAR_SIGN_ERROR = 'CLEAR_SIGN_ERROR';