export const GET_USER_ARTICLES_SUCCESS = 'GET_USER_ARTICLES_SUCCESS';
export const GET_USER_ARTICLES_FAILURE = 'GET_USER_ARTICLES_FAILURE'
export const GET_USER_ARTICLES_LOADING_START = 'GET_USER_ARTICLES_LOADING_START';
